spring.jpa:
  show-sql: true
  hibernate.ddl-auto: create-drop

spring.datasource:
  platform: h2
  url: jdbc:h2:mem:transaction_api

spring.h2.console:
  enabled: true
  settings:
    web-allow-others: true

spring:
  kafka:
    bootstrap-servers: localhost:9092

spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com

